dist: xenial
language: python
python:
  - 3.7
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev daemontools
install:
  - pip install -U pip wheel
  - pip install -r requirements-dev.txt
before_script:
  - flake8 djangopeople
  - flake8 tests
script:
  - psql -c 'CREATE DATABASE djangopeople;' -U postgres
  - python manage.py test
cache: pip
